var ST=function(a,b){window.addEventListener("load",function(){var d=document.getElementById(a),f=d.clientWidth,h=d.clientHeight;d.getContext&&(ctx=d.getContext("2d"),b(new st("st",f,h)))},!1)},ctx=null,debug=function(a,b){if(st.prototype.defaults.debug==!0)switch(a){case "bounds":ctx.lineWidth=2,ctx.strokeStyle="#ff00ff",ctx.beginPath(),ctx.moveTo(b.centerX-30+b.left,b.centerY-30+b.top),ctx.lineTo(b.centerX+30+b.left,b.centerY+30+b.top),ctx.moveTo(b.centerX+30+b.left,b.centerY-30+b.top),ctx.lineTo(b.centerX-
30+b.left,b.centerY+30+b.top),ctx.closePath(),ctx.stroke()}};debug=function(a){console.log(a)};Array.prototype.remove=function(a,b){var d=this.slice((b||a)+1||this.length);this.length=a<0?this.length+a:a;return this.push.apply(this,d)};String.prototype.trim=function(){return this.replace(/^\s*([\s\S]*\S)\s*$/,"$1")};
var frameclip=function(a,b,d,f){this.name=a;this.layer=f;this.width=st.instances[0].width;this.height=st.instances[0].height;this.frameOffset=b;this.lastFrame=d;this.shapes=[];this.callbackfired=!1;this.randomCount=0;this.playMode="";this.tracks=[];this.effects=[];this.sclY=this.sclX=this.scl=1;this.strokeW=this.rot=this.top=this.left=0;this.strokeHex="00000000";this.strokeRGBA=st.prototype.hexRGBA(this.strokeHex);this.strokeR=this.strokeRGBA[0];this.strokeG=this.strokeRGBA[1];this.strokeB=this.strokeRGBA[2];
this.strokeA=this.strokeRGBA[3];this.fillHex="00000000";this.fillRGBA=st.prototype.hexRGBA(this.fillHex);this.fillR=this.fillRGBA[0];this.fillG=this.fillRGBA[1];this.fillB=this.fillRGBA[2];this.fillA=this.fillRGBA[3];this.opac=1;this.centerX=this.width/2;this.centerY=this.height/2;this.cuts=[];this.sprites={}};frameclip.prototype.sprite=function(a,b){this.sprites[a]=b;return this};
frameclip.prototype.shape=function(a,b,d,f,h,i,j,c,l,e,g,k){for(g=0;g<this.shapes.length;g++)if(this.shapes[g].name==a)return this.shapes[g];a=new shapeobject(a,b,d,f,h,i,j,c,l,e,this.layer.depth,k,this);this.shapes.push(a);return a};frameclip.prototype.track=function(a){for(var b=0;b<this.tracks.length;b++)if(this.tracks[b].property==a)return this.tracks[b];this.tracks[this.tracks.length]=new trackprop(a,this);return this.tracks[this.tracks.length-1]};
frameclip.prototype.draw=function(){var a=st.prototype.radians;this.frame=this.layer.frame;ctx.save();if(this.tracks.length>0){for(var b=0;b<this.tracks.length;b++){var d=this.tracks[b],f=this.tracks[b].property;if(d.keys.length<=2){var h=d.keys[0],i=d.keys[1]||d.keys[0];st.prototype.engine(this,this.frame,f,h,i)}else for(var j=0;j<d.keys.length;j++)if(h=d.keys[j],i=d.keys[j+1]||d.keys[j],this.frame>=h.frame&&this.frame<=i.frame){st.prototype.engine(this,this.frame,f,h,i);break}}ctx.translate(this.left+
this.centerX,this.top+this.centerY);ctx.rotate(a(this.rot));this.sclX!=this.sclY?ctx.scale(this.sclX,this.sclY):ctx.scale(this.scl,this.scl);ctx.translate(-this.centerX,-this.centerY);ctx.doFill=!0;ctx.fillStyle="rgba("+this.fillR+","+this.fillG+","+this.fillB+","+this.fillA+")";ctx.strokeStyle="rgba("+this.strokeR+","+this.strokeG+","+this.strokeB+","+this.strokeA+")";if(this.transform)a=this.transform,ctx.transform(a[0],a[1],a[2],a[3],a[4],a[5]);ctx.lineWidth=this.strokeW;ctx.globalAlpha=this.opac;
ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(this.width,0);ctx.lineTo(this.width,this.height);ctx.lineTo(0,this.height);ctx.closePath();ctx.fill();ctx.stroke()}for(b=0;b<this.shapes.length;b++)this.shapes[b].draw(this.frame);for(var c in this.sprites)this.sprites[c].frame<=this.frame?this.sprites[c].draw():this.sprites[c].frame=0;ctx.restore()};
var Img=function(a){this.url=a;this.type="image";this.top=this.left=this.centerY=this.centerX=0;this.scl=1;this.rot=0;this.opac=1;this.transform=[1,0,0,1,0,0];this.f=[];this.a=[];this.c=0;this.tracks=[]};Img.prototype.add=function(a,b){this.a[this.c]=a;this.f[this.c]=b;this.c++};
Img.prototype.render=function(){ctx.save();ctx.translate(this.left+this.centerX,this.top+this.centerY);ctx.scale(this.scl,this.scl);ctx.rotate(st.prototype.radians(this.rot));ctx.translate(-this.centerX,-this.centerY);for(var a=0;a<this.f.length;a++)this.f[a](this.a[a]);ctx.globalAlpha=1;ctx.restore()};var keyframe=function(a,b,d){this.frame=a;this.value=b;this.easing=d};keyframe.prototype.val=function(a){this.v=a};keyframe.prototype.ease=function(a){this.easing=a};
var layer=function(a,b,d){this.name=a;this.depth=b;this.frameclips={};this.mc=d};layer.prototype.frameclip=function(a,b,d){this.frameclips[a]=new frameclip(a,b,d,this);return this.frameclips[a]};layer.prototype.draw=function(){this.frame=this.mc.frame;for(var a in this.frameclips){var b=this.frameclips[a];this.frame>=b.frameOffset&&this.frame<=b.lastFrame&&b.draw()}};var movieclip=function(a,b,d){this.name=a;this.layers=[];this.movieclips=[];this.frame=0;this.length=b;this.loop=d||!1};
movieclip.prototype.layer=function(a,b){var d=new layer(a,b,this);this.layers.push(d);for(var f=[],h=0;h<this.layers.length;h++)f.push(this.layers[h].depth);f.sort(st.sortNumber);var i=[];for(h=0;h<f.length;h++)for(var j=0;j<this.layers.length;j++)this.layers[j].depth==f[h]&&(i[h]=this.layers[j]);this.layers=i;return d};movieclip.prototype.draw=function(){this.drawLayers();if(this.frame==this.length-1){if(this.loop)this.frame=0}else this.frame++};
movieclip.prototype.drawLayers=function(){for(var a=0;a<this.layers.length;a++)this.layers[a].draw()};
var shapeobject=function(a,b,d,f,h,i,j,c,l,e,g,k,p){k=st.prototype.hexRGBA;this.name=a;this.url=b;this.extension=b.split(/([\.][a-zA-Z0-9]+)/)[1];this.obj=[];this.frameclip=p;this.mode=d||"svg";this.checkMemory();this.left=f||0;this.top=h||0;this.scl=i||1;this.rot=j||0;this.strokeW=c||1;this.strokeHex=l||"000000ff";this.strokeRGBA=k(this.strokeHex);this.strokeR=this.strokeRGBA[0];this.strokeG=this.strokeRGBA[1];this.strokeB=this.strokeRGBA[2];this.strokeA=this.strokeRGBA[3];this.fillHex=e||"888888ff";
this.fillRGBA=k(this.fillHex);this.fillR=this.fillRGBA[0];this.fillG=this.fillRGBA[1];this.fillB=this.fillRGBA[2];this.fillA=this.fillRGBA[3];this.opac=1;this.zIndex=g;this.centerY=this.centerX=0;if(d==="svg")this.centerX=this.obj.width/2,this.centerY=this.obj.height/2;this.winding=1;this.type="shape";this.tracks=[];this.effects=[];this.shapes=[];this.transform=[1,0,0,1,0,0]};
shapeobject.prototype.checkMemory=function(){var a=st.instances[0];if(a.urlIndex.length>0){urlMatch=!1;for(var b=0;b<a.urlIndex.length;b++)if(a.urlIndex[b]===this.url){switch(this.mode){case "img":this.obj=st.prototype.loadImage(this.url);break;case "svg":this.obj=st.prototype.loadSVG(this.url,this.mode)}urlMatch=!0;break}if(urlMatch===!1){a.urlIndex[a.urlIndex.length]=this.url;switch(this.mode){case "img":a.ajaxMem[a.urlIndex.length]=st.prototype.loadImage(this.url);break;case "svg":a.ajaxMem[a.urlIndex.length]=
st.prototype.loadSVG(this.url,this.mode)}this.obj=a.ajaxMem[a.urlIndex.length]}}else{a.urlIndex[a.urlIndex.length]=this.url;switch(this.mode){case "img":a.ajaxMem[a.urlIndex.length]=st.prototype.loadImage(this.url);break;case "svg":a.ajaxMem[a.urlIndex.length]=st.prototype.loadSVG(this.url,this.mode)}this.obj=a.ajaxMem[a.urlIndex.length]}};
shapeobject.prototype.track=function(a){for(var b=0;b<this.tracks.length;b++)if(this.tracks[b].property==a)return this.tracks[b];this.tracks[this.tracks.length]=new trackprop(a,this);return this.tracks[this.tracks.length-1]};
shapeobject.prototype.draw=function(a){var b=st.prototype.radians,d,f;for(d=0;d<this.tracks.length;d++){var h=this.tracks[d],i=this.tracks[d].property;if(h.keys.length<=2){var j=h.keys[0],c=h.keys[1]||h.keys[0];st.prototype.engine(this,a,i,j,c)}else for(f=0;f<this.tracks[d].keys.length;f++)if(j=this.tracks[d].keys[f],c=h.keys[f+1]||h.keys[f],a>=j.frame&&a<=c.frame){st.prototype.engine(this,a,i,j,c);break}}ctx.save();ctx.translate(this.left+this.centerX,this.top+this.centerY);ctx.rotate(b(this.rot));
ctx.scale(this.scl,this.scl);ctx.translate(this.left-this.centerX,this.top-this.centerY);ctx.globalAlpha=this.opac;ctx.transform(this.transform[0],this.transform[1],this.transform[2],this.transform[3],this.transform[4],this.transform[5]);this.obj.render();ctx.restore()};var st=function(a,b,d){this.name=a;this.urlIndex=[];this.ajaxMem=[];this.tl="";this.mspf=20;this.frame=0;this.width=b;this.height=d;this.paused=!1;this.movieclips=[];this.lastFrame=0;st.instances.push(this)};st.instances=[];
st.prototype.setFps=function(a){this.mspf=Math.floor(1E3/a)};st.prototype.defaults={ease:"linear",debug:!1};st.prototype.has=function(a,b){return b.indexOf(a,0)>-1};st.prototype.hexRGBA=function(a){return function(a){var d=[];a.replace(/(..)/g,function(a){d.push(parseInt(a,16))});return d}(a)};st.prototype.toHex=function(a){a=a.toString(16);a.length<2&&(a="0".concat(a));return a};st.prototype.radians=function(a){return a/180*Math.PI};st.prototype.ease=function(a,b,d,f,h,i){return h*d/i+f};
st.prototype.engine=function(a,b,d,f,h){var i=this.ease,j=this.hexRGBA;if(b==h.frame){var c=h.value;switch(d){case "left":a.left=c;break;case "top":a.top=c;break;case "centerX":a.centerX=c;break;case "centerY":a.centerY=c;break;case "scl":a.scl=c;break;case "rot":a.rot=c;break;case "mx":a.transform=[c[0],c[1],c[2],c[3],c[4],c[5]];break;case "strokeWeight":a.strokeW=c;break;case "stroke":var l=j(c);a.strokeR=l[0];a.strokeG=l[1];a.strokeB=l[2];a.strokeA=1/255*l[3];break;case "fill":l=j(c);a.fillR=l[0];
a.fillG=l[1];a.fillB=l[2];a.fillA=1/255*l[3];break;case "opac":a.opac=c}}else{var e=f.easing;b-=f.frame;c=f.value;l=h.value-f.value;var g=h.frame-f.frame;switch(d){case "left":a.left=i(e,0,b,c,l,g);break;case "top":a.top=i(e,0,b,c,l,g);break;case "centerX":a.centerX=i(e,0,b,c,l,g);break;case "centerY":a.centerY=i(e,0,b,c,l,g);break;case "scl":a.scl=i(e,0,b,c,l,g);break;case "rot":a.rot=i(e,0,b,c,l,g);break;case "mx":l=[];for(j=0;j<c.length;j++)l[j]=h.value[j]-f.value[j];a.transform=[i(e,0,b,c[0],
l[0],g),i(e,0,b,c[1],l[1],g),i(e,0,b,c[2],l[2],g),i(e,0,b,c[3],l[3],g),i(e,0,b,c[4],l[4],g),i(e,0,b,c[5],l[5],g)];break;case "strokeWeight":a.strokeW=i(e,0,b,c,l,g);break;case "stroke":f=j(f.value);h=j(h.value);a.strokeR=parseInt(i(e,0,b,f[0],h[0]-f[0],g));a.strokeG=parseInt(i(e,0,b,f[1],h[1]-f[1],g));a.strokeB=parseInt(i(e,0,b,f[2],h[2]-f[2],g));a.strokeA=1/255*i(e,0,b,f[3],h[3]-f[3],g);break;case "fill":f=j(f.value);h=j(h.value);a.fillR=parseInt(i(e,0,b,f[0],h[0]-f[0],g));a.fillG=parseInt(i(e,0,
b,f[1],h[1]-f[1],g));a.fillB=parseInt(i(e,0,b,f[2],h[2]-f[2],g));a.fillA=1/255*i(e,0,b,f[3],h[3]-f[3],g);break;case "opac":a.opac=i(e,0,b,c,l,g)}}};st.prototype.start=function(){var a=this;this.timer=setInterval(function(){a.drawNextFrame();if(a.frame>a.lastFrame-1)a.loop?a.frame=0:clearInterval(a.timer)},this.mspf)};st.prototype.mc=function(a){this.movieclips.push(a);if(a.length>this.lastFrame)this.lastFrame=a.length};
st.prototype.drawNextFrame=function(){this.frame<=this.lastFrame&&ctx.clearRect(0,0,this.width,this.height);for(var a=0;a<this.movieclips.length;a++)this.movieclips[a].draw();this.frame++};st.prototype.loadImage=function(a){var b=new Img,d=new Image;d.src=a;b.add([],function(){ctx.drawImage(d,0,0)});return b};
st.prototype.loadSVG=function(a){var b=st.prototype.has,d=st.prototype.hexRGBA,f={},h={},i={},j=[],c,l,e,g=new DOMParser,k=new SVG(a),p=function(a){for(var j=!1,g=!1,q=[],r=[],s=/rgb\(([^\)]+)\)/,n=function(a,b){for(var c=RegExp(a,"g"),d=0,f=[];f[d]=c.exec(b);)d++;return f},u=function(){var a=c.getAttribute("transform");(v=n("(translate[(])([0-99. -]+)(,)([0-99. -]+)",a)[0])&&k.add([v[2],v[4]],function(a){ctx.translate(a[0],a[1])},e);(v=n("(matrix[(])([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)([)])",
a)[0])&&k.add([v[2],v[4],v[6],v[8],v[10],v[12]],function(a){ctx.transform(a[0],a[1],a[2],a[3],a[4],a[5])},e)},A=function(a){var c=g=j=!1,t=!1,y=1,z=1,o=1;if(a=a.getAttribute("style")){a=a.trim().split(";");for(var w=0;w<a.length;w++){var m=a[w].split(":");if(!(m.length<2))switch(o=m[0].trim(),m=m[1].trim(),o){case "opacity":o=m;k.add(o,function(a){ctx.globalAlpha=a},e);break;case "stroke-width":o=parseFloat(m);k.add(o,function(a){ctx.lineWidth=a},e);break;case "stroke-linecap":k.add(m,function(a){ctx.lineCap=
a},e);break;case "stroke-linejoin":k.add(m,function(a){ctx.lineJoin=a},e);break;case "stroke-miterlimit":o=parseFloat(m);k.add(o,function(a){ctx.miterLimit=a},e);break;case "fill-opacity":z=m;break;case "fill":m!="none"&&(j=!0,b("url(#",m)?(o=n("(url[(]#)(.[^)]+)",m)[0][2],m=l.getElementById(o),m.nodeName=="pattern"?k.add(h[o],function(a){ctx.transform.apply(ctx,a[0]);ctx.fillStyle=a[1]},e):(c=!0,k.add(f[o],function(a){ctx.fillStyle=a},e))):b("#",m)?(r=d(m.substr(1,6)),c=!1):b("rgb",m)&&(r=m.replace(s,
"$1"),c=!1));break;case "stroke-opacity":y=m;break;case "stroke":m!="none"&&(g=!0,b("url(#",m)?(o=n("(url[(]#)(.[^)]+)",m)[0][2],m=l.getElementById(o),m.nodeName=="pattern"?k.add(h[o],function(a){ctx.transform.apply(ctx,a[0]);ctx.strokeStyle=a[1]},e):(t=!0,k.add(f[o],function(a){ctx.strokeStyle=a},e))):b("#",m)?(q=d(m.substr(1,6)),t=!1):b("rgb",m)&&(q=m.replace(s,"$1"),t=!1));break;case "clip-path":m=m.replace(/"/g,""),o=n("(url[(]#)(.[^)]+)",m)[0][2],k.add(i[o],function(a){ctx.beginPath();a=n("([a-zA-Z][0-9- .,]+[^a-zA-Z])|(z|Z)",
a.getAttribute("d"));for(var b=0;b<a.length-1;b++){var c=0;switch(a[b][0][0]){case "M":c=n("([0-9-.]+){1,2}",a[b][0]);ctx.moveTo(c[0][0],c[1][0]);break;case "C":c=n("([0-9-.]+){1,6}",a[b][0]);ctx.bezierCurveTo(c[0][0],c[1][0],c[2][0],c[3][0],c[4][0],c[5][0]);break;case "Q":c=n("([0-9-.]+){1,6}",a[b][0]);ctx.quadraticCurveTo(c[0][0],c[1][0],c[2][0],c[3][0]);break;case "A":c=n("([0-9-.]+){1,6}",a[b][0]);ctx.arcTo(c[0][0],c[1][0],c[2][0],c[3][0],c[4][0],c[5][0]);break;case "L":c=n("([0-9-.]+){1,2}",
a[b][0]),ctx.lineTo(c[0][0],c[1][0])}}ctx.clip()},e)}}c==!1&&j==!0&&(c="rgba("+r[0]+","+r[1]+","+r[2]+","+z+")",k.add(c,function(a){ctx.fillStyle=a},e));t==!1&&g==!0&&(c="rgba("+q[0]+","+q[1]+","+q[2]+","+y+")",k.add(c,function(a){ctx.strokeStyle=a},e))}},C=function(){k.add(0,function(){ctx.beginPath()},e);u(c);for(var a=n("([a-zA-Z][0-9- .,]+[^a-zA-Z])|(z|Z)",c.getAttribute("d")),b=0;b<a.length-1;b++){var d=0;switch(a[b][0][0]){case "M":d=n("([0-9-.]+){1,2}",a[b][0]);k.add([d[0][0],d[1][0]],function(a){ctx.moveTo(a[0],
a[1])},e);break;case "C":d=n("([0-9-.]+){1,6}",a[b][0]);k.add([d[0][0],d[1][0],d[2][0],d[3][0],d[4][0],d[5][0]],function(a){ctx.bezierCurveTo(a[0],a[1],a[2],a[3],a[4],a[5])},e);break;case "Q":d=n("([0-9-.]+){1,6}",a[b][0]);k.add([d[0][0],d[1][0],d[2][0],d[3][0]],function(a){ctx.quadraticCurveTo(a[0],a[1],a[2],a[3])},e);break;case "A":d=n("([0-9-.]+){1,6}",a[b][0]);k.add([d[0][0],d[1][0],d[2][0],d[3][0],d[4][0],d[5][0]],function(a){ctx.arcTo(a[0],a[1],a[2],a[3],a[4],a[5])},e);break;case "L":d=n("([0-9-.]+){1,2}",
a[b][0]);k.add([d[0][0],d[1][0]],function(a){ctx.lineTo(a[0],a[1])},e);break;case "Z":k.add(0,function(){ctx.closePath()},e);break;case "z":k.add(0,function(){ctx.closePath()},e)}}A(c);j&&k.add(0,function(){ctx.fill()},e);g&&k.add(0,function(){ctx.stroke()},e)},D=function(){u(c);var a=c.getAttribute("width"),b=c.getAttribute("height"),d=c.getAttribute("x"),f=c.getAttribute("y");A(c);j&&k.add([d,f,a,b],function(a){ctx.fillRect(a[0],a[1],a[2],a[3])},e);g&&k.add([d,f,a,b],function(a){ctx.strokeRect(a[0],
a[1],a[2],a[3])},e)},E=function(a){var b=a.getElementsByTagName("path")[0];a=a.getAttribute("id");i[a]=b},F=function(a){var b=a.getAttribute("id"),c=a.getElementsByTagName("image")[0].getAttribute("xlink:href"),d=new Image;d.src=c;a=n("(matrix[(])([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)(,| )([0-9-. ]+)([)])",a.getAttribute("patternTransform"));d=ctx.createPattern(d,"no-repeat");h[b]=[[a[0][2],a[0][4],a[0][6],a[0][8],a[0][10],a[0][12]],d]},B=function(a,b){var c=a.getAttribute("id");
switch(b){case "linear":var e=a.getAttribute("x1"),h=a.getAttribute("y1"),j=a.getAttribute("x2"),i=a.getAttribute("y2");f[c]=ctx.createLinearGradient(e,h,j,i);for(e=0;h=a.getElementsByTagName("stop")[e];){e++;for(j=0;i=h.getAttribute("style").split(";")[j];){j++;var k=h.getAttribute("offset");i=i.split(":");switch(i[0].trim()){case "stop-color":var g;g=i[1];g.indexOf("#")!=-1?g=d(g.substr(1,6)):(g=g.replace(s,"$1"),g=g.split(","));break;case "stop-opacity":var l=i[1]}}f[c].addColorStop(k,"rgba("+
g[0]+","+g[1]+","+g[2]+","+l+")")}break;case "radial":e=a.getAttribute("cx");h=a.getAttribute("cy");j=a.getAttribute("r");i=a.getAttribute("fx");var n=a.getAttribute("fy");f[c]=ctx.createRadialGradient(e,h,0,i,n,j);for(e=0;h=a.getElementsByTagName("stop")[e];){e++;for(j=0;i=h.getAttribute("style").split(";")[j];)switch(j++,k=h.getAttribute("offset"),i=i.split(":"),i[0].trim()){case "stop-color":g=i[1];g.indexOf("#")!=-1?g=d(g.substr(1,6)):(g=g.replace(s,"$1"),g=g.split(","));break;case "stop-opacity":l=
i[1]}f[c].addColorStop(k,"rgba("+g[0]+", "+g[1]+","+g[2]+","+l+")")}}},x=0;x<a.childNodes.length;x++){c=a.childNodes[x];curTagName=c.tagName;if(a.tagName=="svg")e=c.id;switch(curTagName){case "defs":p(c);break;case "linearGradient":B(c,"linear");break;case "radialGradient":B(c,"radial");break;case "pattern":F(c);break;case "clipPath":E(c);break;case "g":k.add([],function(){ctx.save()},e);u(c);p(c);k.add([],function(){ctx.restore()},e);break;case "path":k.add([],function(){ctx.save()},e);C(c);k.add([],
function(){ctx.restore()},e);break;case "rect":k.add([],function(){ctx.save()},e),D(c),k.add([],function(){ctx.restore()},e)}}};(function(){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);l=g.parseFromString(b.responseText,"text/xml");j=l.documentElement;k.width=parseFloat(j.getAttribute("width"));k.height=parseFloat(j.getAttribute("height"));p(j,"svg")})();return k};st.sortNumber=function(a,b){return a-b};
var SVG=function(a){this.url=a;this.type="SVGobject";this.top=this.left=this.centerY=this.centerX=0;this.scl=1;this.rot=0;this.opac=1;this.transform=[1,0,0,1,0,0];this.f=[];this.a=[];this.c=0;this.tracks=[]};SVG.prototype.add=function(a,b){this.a[this.c]=a;this.f[this.c]=b;this.c++};
SVG.prototype.render=function(){ctx.save();ctx.translate(this.left+this.centerX,this.top+this.centerY);ctx.scale(this.scl,this.scl);ctx.rotate(st.prototype.radians(this.rot));ctx.translate(-this.centerX,-this.centerY);for(var a=0;a<this.f.length;a++)this.f[a](this.a[a]);ctx.globalAlpha=1;ctx.restore()};var trackprop=function(a,b){this.property=a;this.keys=[];this.shape=b};trackprop.prototype.track=function(a){return this.shape.track(a)};
trackprop.prototype.key=function(a,b,d){this.keys.push(new keyframe(a,b,d||st.prototype.defaults.ease));a=[];for(b=0;b<this.keys.length;b++)a[b]=this.keys[b].frame;a.sort(st.sortNumber);d=[];for(b=0;b<this.keys.length;b++)for(var f=0;f<this.keys.length;f++)a[b]==this.keys[f].frame&&(d[b]=this.keys[f]);this.keys=d;return this};
